Hunterised 1.74.2
hunter-packages/leptonica pull request #2
Opened 2017-05-29 07:04 UTC by xsacha

2017-05-29 07:36 UTC, ruslo requested changes

2017-05-29 07:36 UTC, ruslo commented on CMakeLists.txt
> +    find_package(JPEG)
Please check wiki for usage instructions. E.g. it should be `find_package(JPEG CONFIG REQUIRED)` for Jpeg:
* https://github.com/ruslo/hunter/wiki/pkg.jpeg

2017-05-29 07:37 UTC, xsacha commented on CMakeLists.txt
> +    find_package(JPEG)
Thanks,
I'll fix that up

2017-05-30 01:50 UTC, xsacha commented
This one works now.
Thanks.

2017-05-30 12:03 UTC, ruslo approved these changes

2017-05-30 12:03 UTC, merged

2017-05-30 12:04 UTC, ruslo commented
Released:
* https://github.com/hunter-packages/leptonica/releases/tag/v1.74.2-p0