Just link targets directly. No need to check.
hunter-packages/leptonica pull request #5
Opened 2017-06-02 02:57 UTC by xsacha

Also add find_package's to Config so targets are always resolved.

2017-06-02 09:18 UTC, ruslo requested changes

2017-06-02 09:18 UTC, ruslo commented on src/CMakeLists.txt
> +target_link_libraries           (leptonica JPEG::jpeg PNG::png TIFF::libtiff ZLIB::zlib)
I think we need `PUBLIC` in this case.

2017-06-02 09:18 UTC, ruslo commented on cmake/templates/LeptonicaConfig.cmake.in
> +find_package(JPEG CONFIG)
`CONFIG REQUIRED`?

2017-06-04 02:29 UTC, xsacha commented on src/CMakeLists.txt
> +target_link_libraries           (leptonica JPEG::jpeg PNG::png TIFF::libtiff ZLIB::zlib)
Added PUBLIC and nothing changed. What was meant to happen?

2017-06-04 02:31 UTC, xsacha commented on cmake/templates/LeptonicaConfig.cmake.in
> +find_package(JPEG CONFIG)
My thoughts were that the REQUIRED is already used in the CMakeLists so this find_package will succeed regardless.

2017-06-05 11:26 UTC, ruslo requested changes

2017-06-05 11:26 UTC, ruslo commented on src/CMakeLists.txt
> +target_link_libraries           (leptonica JPEG::jpeg PNG::png TIFF::libtiff ZLIB::zlib)
> nothing changed

Nothing where? PUBLIC means that dependency of the Leptonica should link jpeg, png, tiff and zlib too. I.e. Leptonica itself will build/install fine, but problems will appear on user's side when library used.

2017-06-05 12:41 UTC, xsacha commented on src/CMakeLists.txt
> +target_link_libraries           (leptonica JPEG::jpeg PNG::png TIFF::libtiff ZLIB::zlib)
The example app already gets these libraries as an interface link with the target.
This didn't change when adding PUBLIC and I wouldn't expect it to.

2017-06-05 12:53 UTC, ruslo commented on src/CMakeLists.txt
> +target_link_libraries           (leptonica JPEG::jpeg PNG::png TIFF::libtiff ZLIB::zlib)
May be so, not ready to show any example. I'm just using `PUBLIC` for simplicity always.

2017-06-05 12:58 UTC, xsacha commented on src/CMakeLists.txt
> +target_link_libraries           (leptonica JPEG::jpeg PNG::png TIFF::libtiff ZLIB::zlib)
OK, well I just added it anyway.

2017-06-05 13:01 UTC, ruslo approved these changes

2017-06-05 13:01 UTC, merged

2017-06-05 13:02 UTC, ruslo commented
https://github.com/hunter-packages/leptonica/releases/tag/v1.74.2-p3